grafana:
  baseurl: https://localhost/grafana/render/d-solo/
  dashboard: xxx/some-dashboard
  apikey: 12345
  pngwidth: 128
  pngheight: 128
metrics:
  baseurl: http://localhost/api/metrics/
  apikey: 12345
update:
  interval: 60000
signs:
images:
