name: MinecraftNOC
version: ${project.version}
main: com.opennms.minecraftnoc.MinecraftNOC
api-version: 1.15
authors: [XeroCrossing]
description: In-game OpenNMS NOC screens

commands:
  getpng:
    description: Fetch a PNG from the specified panel on the current dashboard
  getmetric:
    description: Fetch a metric text from the specified URL
  dashboard:
    description: Manage image dashboards
